# -*- coding: utf-8 -*-
"""Inflation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GD6MjVKrk7_y0l50nAFwFvNgjOo0ru0A
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas
df = pandas.read_csv ('/content/gdrive/MyDrive/898.csv', delimiter='\t', 
                 names = ['WebPriceId', 'DateObserve', 'StockStatus', 'CurrentPrice']).head()


#df = pandas.read_csv('/content/gdrive/MyDrive/898.csv', index_col=0)
df.head(50)

import datetime #находим минимальную дату продаж
dt0 = datetime.datetime.now()
i=0
for dt in df.DateObserve:
  dt = df.DateObserve[i]
  i += 1
  if dt[0:4] == 'Date':                   #Убирает первую строку с названием столбца
    continue
  else:
    data = datetime.datetime( int(dt[0:4]), int(dt[5:7]), int(dt[8:10]))
    #print(data)
    if data < dt0:
      dt0 = data
dt00 = dt0.strftime("%Y %m%")[0:7]  
print(dt00)

import datetime #находим максимальную дату продаж
dtm = dt0
i=0
for dt in df.DateObserve:
  dt = df.DateObserve[i]
  i += 1
  if dt[0:4] == 'Date':                   #Убирает первую строку с названием столбца
    continue
  else:
    data = datetime.datetime( int(dt[0:4]), int(dt[5:7]), int(dt[8:10]))
    #print(data)
    if data > dtm:
      dtm = data
dtmm = dtm.strftime("%Y %m%")[0:7] 
print(dtmm)

if dtmm[0:4] == dt00[0:4]:
  count = int(dtmm[6:8])-int(dt00[6:8])
else:
  count= int(dtmm[0:4])-int(dt00[0:4])*12 + int(dtmm[6:8])-int(dt00[6:8])

i=0
for t in df.DateObserve:
  t = df.DateObserve[i]
  i += 1
  if t[0:4] == 'Date':                   #Убирает первую строку с названием столбца
    continue
  else:
    data =  t[0:4] + t[5:7]
  j=0
  for j in range(count+1):
    if int(data[0:4]) == int(dt00[0:4]):
      if (int(data[5:7]) == int(dt00[5:7]) + (int('0') + j)) and (int(dt00[5:7]) + (int('0') + j)) <= 12:
        j += 1
        dt = j
        print(dt)
      elif (int(dt00[5:7]) + (int('0') + j)) > 12:
        dt00[0:4] = int(dt00[0:4]) + 1
        dt00[5:7] = int('01')

ID0 = df.WebPriceId[1] #берем первые, так в [0] хранятся имна столбцов, хранят цену на предыдущий месяц
DT0 = df.DateObserve[1]
AK0 = df.StockStatus[1]               #загоняем все числа в список
PR0 = df.CurrentPrice[1]
s=[]
k=1 
i=0                      # k - отражающет номер вхождения строки
for DT1 in df.DateObserve:
  if k <= 2:
    ID1 = df.WebPriceId[2] # вторые аргументы для сравнения. хранят цену на текущий месяц
    DT1 = df.DateObserve[1]
    AK1 = df.StockStatus[1]
    PR1 = df.CurrentPrice[1]
    k += 1
  else: 
    if ID1 == ID0:
      if ID1 == 'InStock':
        if DT1 == DT0:
          s[k] = (PR1/PR0) - 1